<?php
include('fn.php');
 $sno=$_GET['x'];


$query2="select uid,p_id from listing where sno=$sno";
  $executeq2=mysqli_query($con,$query2);
  $countq2=mysqli_num_rows($executeq2);
  if ($countq2>0) {
     $row=mysqli_fetch_array($executeq2);
  $uid=$row['uid'];
  $pid=$row['p_id'];
  }
  else{
    msg('error generated by highamount.php');
    sendto('http://krishi.rf.gd/customer/cindexfa.php');
}

 $qr1="select max(amount) from tempdata where fa_id=$uid and pid=$pid";
  $rs1=mysqli_query($con,$qr1);
  $count=mysqli_num_rows($rs1);
  $row=mysqli_fetch_array($rs1);
  $hiam=$row['max(amount)'];
  if (!is_null($hiam)) {
        echo $hiam;
  }else echo 0;
  
  
?>